"""add missing spec fields: User.total_returns, Odds.game_start_time

Revision ID: 3185919a484b
Revises: 3dd14bc8355e
Create Date: 2026-09-01 16:43:45.615186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3185919a484b'
down_revision: Union[str, None] = '3dd14bc8355e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odds', sa.Column('game_start_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('total_returns', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_returns')
    op.drop_column('odds', 'game_start_time')
    # ### end Alembic commands ###
