"""Initial schema: users, bets, games, odds, team_stats

Revision ID: 3dd14bc8355e
Revises: 
Create Date: 2026-09-01 15:43:39.558162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd14bc8355e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('sport', sa.Enum('NFL', 'CFB', name='sport'), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('final_score_home', sa.Integer(), nullable=True),
    sa.Column('final_score_away', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'COMPLETED', name='gamestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=10), nullable=False),
    sa.Column('sport', sa.Enum('NFL', 'CFB', name='sport'), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('stat_key', sa.String(length=100), nullable=False),
    sa.Column('stat_value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('initial_bankroll', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=20), nullable=True),
    sa.Column('sportsbook', sa.Enum('DRAFTKINGS', 'FANDUEL', 'KALSHI', 'CUSTOM', name='sportsbook'), nullable=False),
    sa.Column('bet_type', sa.Enum('SPREAD', 'MONEYLINE', 'OVER_UNDER', 'PROP', 'CUSTOM', name='bettype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('picked_side', sa.String(length=255), nullable=False),
    sa.Column('odds_at_placement', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', 'PUSH', name='betstatus'), nullable=True),
    sa.Column('payout', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('game_start_time', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('sportsbook', sa.Enum('DRAFTKINGS', 'FANDUEL', 'KALSHI', 'CUSTOM', name='sportsbook'), nullable=False),
    sa.Column('bet_type', sa.Enum('SPREAD', 'MONEYLINE', 'OVER_UNDER', 'PROP', 'CUSTOM', name='bettype'), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odds')
    op.drop_table('bets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('team_stats')
    op.drop_table('games')
    # ### end Alembic commands ###
