"""add side field to odds table

Revision ID: 4c2a3b5d1e9f
Revises: 3185919a484b
Create Date: 2026-09-01 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2a3b5d1e9f'
down_revision: Union[str, None] = '3185919a484b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odds', sa.Column('side', sa.String(100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odds', 'side')
    # ### end Alembic commands ###
