"""Rename bets.odds_at_placement to bets.odds_locked_at

The model was renamed when line locking was added, but no migration
followed, so the deployed Postgres schema still had the old column and
every profile read failed with UndefinedColumn.

Expressed as a rename rather than the autogenerated add+drop so existing
odds are preserved. batch_alter_table keeps it portable to SQLite.

Revision ID: dc546b783b9a
Revises: 4c2a3b5d1e9f
Create Date: 2026-09-03 11:51:56.244329

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dc546b783b9a'
down_revision: Union[str, None] = '4c2a3b5d1e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('bets') as batch_op:
        batch_op.alter_column('odds_at_placement', new_column_name='odds_locked_at')


def downgrade() -> None:
    with op.batch_alter_table('bets') as batch_op:
        batch_op.alter_column('odds_locked_at', new_column_name='odds_at_placement')
